[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.9.23, pytest-8.3.5, pluggy-1.5.0 -- /workspace/PoC_env/CVE-2023-30172/bin/python
cachedir: .pytest_cache
rootdir: /workspace/mlflow
configfile: pytest.ini
plugins: cov-6.1.1, localserver-0.5.0
[1mcollecting ... [0mcollected 0 items / 1 error

==================================== ERRORS ====================================
[31m[1m____________ ERROR collecting tests/tracking/test_rest_tracking.py _____________[0m
[31mImportError while importing test module '/workspace/mlflow/tests/tracking/test_rest_tracking.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/root/miniconda3/envs/py_39/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tracking/test_rest_tracking.py:21: in <module>
    from mlflow.server.handlers import validate_path_is_safe
E   ImportError: cannot import name 'validate_path_is_safe' from 'mlflow.server.handlers' (/workspace/mlflow/mlflow/server/handlers.py)[0m
[33m=============================== warnings summary ===============================[0m
conftest.py:38
  /workspace/mlflow/conftest.py:38: PytestRemovedIn9Warning: The (path: py.path.local) argument is deprecated, please use (collection_path: pathlib.Path)
  see https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path
    @pytest.hookimpl(hookwrapper=True)

mlflow/utils/autologging_utils/versioning.py:6
  /workspace/mlflow/mlflow/utils/autologging_utils/versioning.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import resource_filename

../PoC_env/CVE-2023-30172/lib/python3.9/site-packages/pkg_resources/__init__.py:3147
  /workspace/PoC_env/CVE-2023-30172/lib/python3.9/site-packages/pkg_resources/__init__.py:3147: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[36m[1m=========================== short test summary info ============================[0m
[31mERROR[0m tests/tracking/test_rest_tracking.py
[31m========================= [33m3 warnings[0m, [31m[1m1 error[0m[31m in 0.78s[0m[31m =========================[0m

------------------------------ Standard Error ------------------------------
ERROR: found no collectors for /workspace/mlflow/tests/tracking/test_rest_tracking.py::test_path_validation

ERROR: found no collectors for /workspace/mlflow/tests/tracking/test_rest_tracking.py::test_validate_path_is_safe_good

ERROR: found no collectors for /workspace/mlflow/tests/tracking/test_rest_tracking.py::test_validate_path_is_safe_bad


------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail