[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
<empty>
------------------------------ Standard Error ------------------------------
E
======================================================================
ERROR: test_file_open_suffix (trytond.tests.test_tools.ToolsTestCase)
Test file_open from same root name but with a suffix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trytond/tests/test_tools.py", line 134, in test_file_open_suffix
    file_open('../trytond_suffix', subdir=None)
  File "trytond/tools/misc.py", line 75, in file_open
    name = secure_join(root_path, name)
  File "trytond/tools/misc.py", line 38, in secure_join
    if os.path.commonpath([root, path]) != root:
AttributeError: 'module' object has no attribute 'commonpath'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail