[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
--- FAIL: Test_GetPluginAssets (0.09s)
    --- FAIL: Test_GetPluginAssets/Given_a_request_for_a_relative_path (0.01s)
        plugins_test.go:87: 
            	Error Trace:	plugins_test.go:87
            	            				plugins_test.go:211
            	Error:      	Not equal: 
            	            	expected: 404
            	            	actual  : 403
            	Test:       	Test_GetPluginAssets/Given_a_request_for_a_relative_path
        --- FAIL: Test_GetPluginAssets/Given_a_request_for_a_relative_path/When_calling_GET_on_/public/plugins/test-plugin/../3916670903 (0.01s)
            testing.go:1679: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
FAIL
FAIL	github.com/grafana/grafana/pkg/api	0.122s
FAIL

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail